# Generated by Django 3.1 on 2020-08-30 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('contenido', models.TextField()),
                ('fecha_creado', models.DateTimeField()),
                ('fecha_modificado', models.DateTimeField()),
                ('permitir_comentarios', models.BooleanField(default=True)),
            ],
        ),
    ]
