# Generated by Django 3.1 on 2020-09-09 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0002_auto_20200907_1945'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tablaintermedia',
            new_name='CalificacionPost',
        ),
        migrations.AlterField(
            model_name='post',
            name='usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='post_creados', to=settings.AUTH_USER_MODEL),
        ),
    ]
