# Generated by Django 3.1 on 2020-09-09 22:52

from django.db import migrations, models
import post.validators


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20200909_1919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-fecha_creado',), 'verbose_name': 'post_singular', 'verbose_name_plural': 'post_plural'},
        ),
        migrations.AlterField(
            model_name='calificacionpost',
            name='calificacion',
            field=models.IntegerField(validators=[post.validators.validate_valor_calificacion]),
        ),
    ]
